modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "depression"
version = "${version}"
displayName = "Depression"
authors = "block_137, SimoTCD, TheMoonAries, Tianxin_Limao, hhxkzhy"
description = '''
This is a mod that adds brand-new emotion and mental health mechanism to Minecraft!
'''
logoFile = "assets/depression/icon.png"

[[dependencies.depression]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.depression]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.depression]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
